<#
.SYNOPSIS
    --.
.DESCRIPTION
    Preinstall.ps1, triggered by preinstall.cmd
    Application Checking PreFlight script to confirm some applications are at specific levels, or the script will fail the upgrade out early, making reporting easier.

    Update the $AppChecks variable to check for additional apps. Add as many versions as you want to "Approve" to be allowed
.INPUTS
    None.
.OUTPUTS
    None.
.NOTES
    Created by @gwblok
.LINK
    https://garytown.com
.LINK
    https://www.recastsoftware.com
.COMPONENT
    --
.FUNCTIONALITY
    --
#>

## Set script requirements
#Requires -Version 3.0

##*=============================================
##* VARIABLE DECLARATION
##*=============================================
#region VariableDeclaration

#Registry Path that will get Tagged
$registryPath = "HKLM:\SOFTWARE\WaaS"
$TimeStamp = Get-Date -f s
$keyname = "CA_PreInstall_Run"
New-ItemProperty -Path $registryPath -Name $keyname -Value $TimeStamp -Force

#Check for these Installed Applications and make sure they match these versions, or the script will exit with error
$AppChecks = @(

@{ AppName = "GreenShot%"; Version = ("1.3.10.6","1.2.10.6")}
@{ AppName = "Dell Command | Monitor"; Version = ("10.3.1.138")}
@{ AppName = "7-zip%"; Version = ("20.00")}
@{ AppName = "OBS Studio"; Version = ("25.0.8")}
)

#Logfile generated by this script
$WaaSFolder = "$($env:ProgramData)\WaaS"
$logfile = "$WaaSFolder\CustomActions.log"

## Get script path and name
[string]$ScriptPath = [System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)
[string]$ScriptName = [System.IO.Path]::GetFileNameWithoutExtension($MyInvocation.MyCommand.Definition)

#endregion
##*=============================================
##* END VARIABLE DECLARATION
##*=============================================

##*=============================================
##* SCRIPT BODY
##*=============================================
#region ScriptBody


#Confirm LogFile Folder
if (!(Test-Path $WaaSFolder)){$NewFolder = new-item -Path $WaaSFolder -ItemType Directory -Force}


ForEach ($AppCheck in $AppChecks)
    {
    $CurrentAppVersion = $null
    $CurrentAppVersion = [system.version](Get-WmiObject -Namespace 'root\cimv2\sms' -Query "SELECT ProductVersion FROM SMS_InstalledSoftware where ARPDisplayName like '$($AppCheck.AppName)'").ProductVersion
    [system.version[]]$CurrentAppRequiredVersion = ($AppCheck.Version)
    if ($CurrentAppVersion)
        {
        if ($CurrentAppVersion -in $CurrentAppRequiredVersion)
            {
            Write-Output "Found: $($AppCheck.AppName) with Correct Version: $CurrentAppVersion"
            }
        else
            {
            Write-Output "Found: $($AppCheck.AppName) - WRONG Version!! - Needs: $($AppCheck.Version) | Has: $CurrentAppVersion"
            $exitcode = "253"
            }
        }
    else
        {
        Write-Output "Not Found: App $($AppCheck.AppName)"
        }
    }
if ($ExitCode){CMTraceLog -Message  "Exit Code: $ExitCode" -Type 1 -LogFile $LogFile}
exit $exitcode
#endregion
##*=============================================
##* END SCRIPT BODY
##*=============================================